[RFC] Remove the need for the python to startup Plex
comio/plex-overlay pull request #14
Opened 2020-09-23 02:28 UTC by anthonyryan1

This isn't quite fully baked yet, but it's a step in the correct direction I believe based on the discussions going on at the end of this thread: https://forums.plex.tv/t/when-will-plex-media-server-shift-to-python-3/600689

Bringing it up as a pull request to get the discussion rolling on further changes needed.

Next tasks would include:
* Installing the systemd script
* scanelf: rpath_security_checks() warnings when installing

2020-09-25 13:47 UTC, comio commented
Please can switch to 1.20.2 package?

2020-09-25 13:48 UTC, comio commented on media-tv/plex-media-server/plex-media-server-1.20.1-r1.ebuild
> +	_mask_plex_libraries_revdep
you need patchelf to fix _codecs_kr.so I think

2020-09-25 14:00 UTC, comio requested changes

2020-09-25 14:00 UTC, comio commented on media-tv/plex-media-server/plex-media-server-1.20.1-r1.ebuild
> +	_mask_plex_libraries_revdep
```
+	# Fix RPATH
+	patchelf --force-rpath --set-rpath '$ORIGIN:$ORIGIN/../../../../../../lib' "${ED}"/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/lib-dynload/_codecs_kr.so || die
+

```

2020-09-25 14:00 UTC, comio commented on media-tv/plex-media-server/plex-media-server-1.20.1-r1.ebuild
> +	systemd_newunit "${FILESDIR}/systemd/${PN}.service" "${PN}.service"
```
systemd_newunit "${ED}"/usr/lib/plexmediaserver/lib/plexmediaserver.service
```
We already apply a patch to fix PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION using the Gentoo Profile

2020-09-27 13:33 UTC, anthonyryan1 commented
I'll get the other changes done in a moment, but the Plex developers said [altering the RPATH isn't correct](https://forums.plex.tv/t/when-will-plex-media-server-shift-to-python-3/600689/24), I've also noticed no issues since we stopped changing the RPATH in my local install.

How did you determine the RPATH modifications need to be re-added?

2020-09-28 18:25 UTC, anthonyryan1 commented
Closing based on the adapted version merged into the master already.

2020-09-28 18:25 UTC, closed without merging

2020-09-29 07:08 UTC, comio commented
> I'll get the other changes done in a moment, but the Plex developers said [altering the RPATH isn't correct](https://forums.plex.tv/t/when-will-plex-media-server-shift-to-python-3/600689/24), I've also noticed no issues since we stopped changing the RPATH in my local install.
> 
> How did you determine the RPATH modifications need to be re-added?

I just copied from other _codecs_*.so:

```
scanelf -r /var/tmp/portage/media-tv/plex-media-server-1.20.2-r1/image/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/lib-dynload/_codecs_jp.so
 TYPE   RPATH FILE 
ET_DYN $ORIGIN:$ORIGIN/../../../../../../lib /var/tmp/portage/media-tv/plex-media-server-1.20.2-r1/image/usr/lib/plexmediaserver/Resources/Python/lib/python2.7/lib-dynload/_codecs_jp.so 
```